general.live_config_reload = true

general.import = [
    # "~/.config/alacritty/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/one_dark.toml"
    "~/.config/alacritty/themes/dracula_plus.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
blur = true
startup_mode = "Maximized"   # Windowed | Maximized | Fullscreen | SimpleFullscreen

[window.dimensions]
columns = 200
lines = 40

[window.padding]
x = 5
y = 0

[font]
size = 15

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"
